server:
  port: 3000
logging:
  level:
    ru.ohapegor: DEBUG
jwt:
  secret: change_it
  issuer: example.io

spring:
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:./users_db;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9090
    password: password
    username: sa